### ISSUE TITLE
Issue with connecting

### ISSUE THREAD

**Issue by ramanthanc** [motradingapi/NodeJSSDK#1]
It says let MofslOpenApi = require('./MOFSLOPENAPI_NodejsV2.1'); but no file found, if we change the file to MOFSLOPENAPI_V2.2' even it says vendorId is needed(eventhough i am not a vendor), if we give dummy vendorID, i am not getting the vendorid error. Then getting mac address not specified if we change source to DESKTOP, the error is gone, Then getting productversion is missing. 

Full of errors, pls help us in connecting to socket. I am fed up with trying and fixing those.

**Comment by motradingapi** [comment]
Consider the Vendor ID as Client ID while login.
You will get functions to set MAC/IP address in sample file.
Please run the sample file attached in SDK with your login credentials.

**Comment by ramanthanc** [comment]
This answer doesn't answer the productversion and source queries, Also where can i find the vendorid and client id in portal. I have setup userid, password and apikey. I am not clear with your response

**Comment by krishn-kant-raj** [comment]
Please go through the implementation guide and run the sample file. You need to change the first line of sample file which is

let MofslOpenApi = require('./MOFSLOPENAPI_NodejsV2.2');


Use your below required login credentials and pass these parameters while login:

userID = "";
password = "";
PANorDOB = "";
Apikey= "";
vendorId = ""; //Same as userID
totp = "";  //Google Authenticator OTP

**Comment by ramanthanc** [comment]
I am getting this error, when i do as per guide, if i keep sourceId to WEB

LOGIN ::  {
  status: 'ERROR',
  message: 'MacAddress is Invalid In Header Parameter',
  errorcode: 'MO2008',
  data: null
}
*********************************************
undefined
{
  status: 'FAILED',
  message: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"
      at ClientRequest.setHeader (node:_http_outgoing:579:3)
      at new ClientRequest (node:_http_client:262:14)
      at Object.request (node:https:353:10)
      at RedirectableRequest._performRequest (/home/machine-three/Documents/NodeJSSDK-main/node_modules/follow-redirects/index.js:296:24)
      at new RedirectableRequest (/home/machine-three/Documents/NodeJSSDK-main/node_modules/follow-redirects/index.js:69:8)
      at Object.request (/home/machine-three/Documents/NodeJSSDK-main/node_modules/follow-redirects/index.js:535:14)
      at dispatchHttpRequest (/home/machine-three/Documents/NodeJSSDK-main/node_modules/axios/lib/adapters/http.js:179:25)
      at new Promise (<anonymous>)
      at httpAdapter (/home/machine-three/Documents/NodeJSSDK-main/node_modules/axios/lib/adapters/http.js:21:10)
      at dispatchRequest (/home/machine-three/Documents/NodeJSSDK-main/node_modules/axios/lib/core/dispatchRequest.js:52:10) {
    code: 'ERR_HTTP_INVALID_HEADER_VALUE'
  },
  errorcode: '',
  AuthToken: ''
}

if i change sourceid it to DESKTOP, i am getting below error
ERROR ::  TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "productversion"
    at ClientRequest.setHeader (node:_http_outgoing:579:3)
    at new ClientRequest (node:_http_client:262:14)
    at Object.request (node:https:353:10)
    at RedirectableRequest._performRequest (/home/machine-three/Documents/NodeJSSDK-main/node_modules/follow-redirects/index.js:296:24)
    at new RedirectableRequest (/home/machine-three/Documents/NodeJSSDK-main/node_modules/follow-redirects/index.js:69:8)
    at Object.request (/home/machine-three/Documents/NodeJSSDK-main/node_modules/follow-redirects/index.js:535:14)
    at dispatchHttpRequest (/home/machine-three/Documents/NodeJSSDK-main/node_modules/axios/lib/adapters/http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (/home/machine-three/Documents/NodeJSSDK-main/node_modules/axios/lib/adapters/http.js:21:10)
    at dispatchRequest (/home/machine-three/Documents/NodeJSSDK-main/node_modules/axios/lib/core/dispatchRequest.js:52:10) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}

pls test from your end and let me know, i have done everything as per last comment

**Comment by ramanthanc** [comment]
@krishn-kant-raj, could you pls look into the above comments and help me

**Comment by ramanthanc** [comment]
Hi team, waiting for your response.

**Comment by motradingapi** [comment]
Dear @ramanthanc, Please provide your contact details (Phone number, Email ID) and Issue details on tradingapi@motilaloswal.com.
Please mention "Github-NodeJSSDK Issue" in the subject line.

We'll connect over phone call to provide best resolution.

**Comment by ramanthanc** [comment]
i have send the email, pls revert back ASAP

**Comment by ramanthanc** [comment]
HI Team, i am waiting for your getback.

**Comment by ramanthanc** [comment]
HI @krishn-kant-raj @motradingapi, waiting for your response for a long time.

**Comment by motradingapi** [comment]
> i have send the email, pls revert back ASAP

Dear @ramanthanc, We haven't received your e-mail. Can you please send us your communication details over e-mail

**Comment by ramanthanc** [comment]
I have sent continuous email to tradingapi@motilaloswal.com, To make sure we are on same mail loop could you pls send a mail to ramanathanc.c@gmail.com.
